---
- name: Determine if remote control is enabled
  ansible.builtin.set_fact:
    __remote_control_any_enabled: "{{ deploy_remote_control | default(false) | bool }}"

- name: Deploy remote control
  ansible.builtin.import_tasks: deploy_remote_control.yaml

- name: Undeploy remote control
  ansible.builtin.import_tasks: undeploy_remote_control.yaml
