- name: Create Grafana configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: root
    group: root
  with_items:
    - "/app/grafana/conf"
    - "/app/grafana/conf/provisioning"
    - "/app/grafana/conf/provisioning/datasources"
    - "/app/grafana/conf/provisioning/dashboards"
    - "/app/grafana/conf/provisioning/alerting"
    - "/app/grafana/conf/provisioning/plugins"
    - "/app/grafana/conf/provisioning/dashboards/system"

- name: Copy datasource file
  ansible.builtin.copy:
    content: |
      apiVersion: 1

      datasources:
        - name: Prometheus
          type: prometheus
          access: proxy
          uid: prometheus_ds
          url: https://prometheus.{{ internal_domain }}
          isDefault: true
          # Used to compare versions when updating.
          version: 1
          editable: false

    dest: /app/grafana/conf/provisioning/datasources/prometheus.yaml
    mode: "0644"
    owner: root
    group: root

- name: Copy node_exporter dashboard config
  ansible.builtin.copy:
    content: |
      apiVersion: 1

      providers:
        - name: prometheus_ds
          folder: 'system'
          type: file
          disableDeletion: true
          # how often Grafana will scan for changed dashboards
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /opt/grafana/conf/provisioning/dashboards/system/node_exporter_full.json
            foldersFromFilesStructure: true

    dest: /app/grafana/conf/provisioning/dashboards/node_exporter.yaml
    mode: "0644"
    owner: root
    group: root

- name: Copy ping_exporter dashboard config
  ansible.builtin.copy:
    content: |
      apiVersion: 1

      providers:
        - name: prometheus_ds
          folder: 'system'
          type: file
          disableDeletion: true
          # how often Grafana will scan for changed dashboards
          updateIntervalSeconds: 10
          allowUiUpdates: false
          options:
            path: /opt/grafana/conf/provisioning/dashboards/system/ping_exporter.json
            foldersFromFilesStructure: true

    dest: /app/grafana/conf/provisioning/dashboards/ping_exporter.yaml
    mode: "0644"
    owner: root
    group: root

- name: Copy node_exporter full dashboard
  ansible.builtin.copy:
    # https://grafana.com/grafana/dashboards/1860-node-exporter-full/
    src: dashboards/node_exporter_full_1860_rev37.json
    dest: /app/grafana/conf/provisioning/dashboards/system/node_exporter_full.json
    mode: "0644"
    owner: root
    group: root

- name: Copy ping exporter dashboard
  ansible.builtin.template:
    src: network.json.j2
    dest: /app/grafana/conf/provisioning/dashboards/system/ping_exporter.json
    mode: "0644"
    owner: root
    group: root

- name: Copy grafana.ini configuration
  ansible.builtin.copy:
    content: |
      [security]
      admin_user = admin
      admin_password = {{ grafana_password | default(admin) }}
      disable_initial_admin_creation = false

    dest: /app/grafana/conf/grafana.ini
    mode: "0644"
    owner: root
    group: root
  notify: Restart Grafana service

- name: Create grafana.service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Podman container-grafana.service
      Documentation=man:podman-generate-systemd(1)
      Wants=network-online.target
      After=network-online.target
      RequiresMountsFor=%t/containers

      [Service]
      Environment=PODMAN_SYSTEMD_UNIT=%n
      Restart=on-failure
      TimeoutStopSec=70
      ExecStart=/usr/bin/podman run \
              --cidfile=%t/%n.ctr-id \
              --cgroups=no-conmon \
              --rm \
              --sdnotify=conmon \
              --replace \
              -d \
              --name grafana \
              -v /app/grafana/conf:/opt/grafana/conf \
              -e "GF_PATHS_CONFIG=/opt/grafana/conf/grafana.ini" \
              -e "GF_PATHS_PROVISIONING=/opt/grafana/conf/provisioning" \
              --label="traefik.enable=true" \
              --label="traefik.http.routers.grafana.rule=Host(`grafana.{{ internal_domain }}`)" \
              --label="traefik.http.routers.grafana.entrypoints=websecure" \
              --label="traefik.http.routers.grafana.tls.certresolver=letsencrypt" \
              --label="traefik.http.routers.grafana.tls.domains[0].main=grafana.{{ internal_domain }}" \
              --label="traefik.http.services.grafana.loadbalancer.server.port=3000" \
              --dns=172.16.255.254 \
              docker.io/grafana/grafana-oss:11.0.0
      ExecStop=/usr/bin/podman stop \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      ExecStopPost=/usr/bin/podman rm \
              -f \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      Type=notify
      NotifyAccess=all

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/grafana.service
    mode: "0644"
  register: grafana_service_unit
  notify:
    - Reload systemd daemons
    - Restart Grafana service

- name: Enable and start grafana service
  ansible.builtin.systemd_service:
    name: grafana.service
    enabled: true
    state: started
