---
- name: Restart NUT driver scheduler
  ansible.builtin.systemd_service:
    name: nut-driver-scheduler
    state: restarted

- name: Restart NUT server
  ansible.builtin.systemd_service:
    name: nut-server
    state: restarted

- name: Restart NUT monitor
  ansible.builtin.systemd_service:
    name: nut-monitor
    state: restarted
