---
- name: Reload systemd daemons for vpn role
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart netbird network
  ansible.builtin.systemd_service:
    state: restarted
    name: netbird-network

- name: Restart netbird-dashboard service
  ansible.builtin.systemd_service:
    state: restarted
    name: netbird-dashboard

- name: Restart netbird-signal service
  ansible.builtin.systemd_service:
    state: restarted
    name: netbird-signal

- name: Restart netbird-relay service
  ansible.builtin.systemd_service:
    state: restarted
    name: netbird-relay

- name: Restart protonvpn network
  ansible.builtin.systemd_service:
    state: restarted
    name: protonvpn-network

- name: Restart protonvpn service
  ansible.builtin.systemd_service:
    state: restarted
    name: protonvpn
