---
- name: Reload systemd daemons for mqtt-broker role
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart MQTT broker service
  ansible.builtin.systemd_service:
    name: mqtt-broker
    state: restarted
  ignore_errors: true