---
# This workaround is needed because the current release of Bitwarden Secret Manager is bugged and
# two variables cannot be used at the same time.
# https://community.bitwarden.com/t/bitwarden-lookup-plugin-for-ansible-causes-panick-errors-and-a-worker-was-found-in-a-dead-state/64579/7
- name: Bitwarden workaround for p2p_radarr_api_key
  ansible.builtin.set_fact:
    p2p_radarr_api_key: "{{ p2p_radarr_api_key }}"

- name: Ensure root folder exists in Radarr
  devopsarr.radarr.radarr_root_folder:
    radarr_url: "{{ _p2p_radarr_server_url }}"
    radarr_api_key: "{{ p2p_radarr_api_key }}"
    path: "{{ p2p_radarr_container_data_dir }}"

- name: Ensure download client exists in Radarr
  devopsarr.radarr.radarr_download_client:
    radarr_url: "{{ _p2p_radarr_server_url }}"
    radarr_api_key: "{{ p2p_radarr_api_key }}"
    remove_completed_downloads: true
    remove_failed_downloads: true
    enable: true
    priority: 1
    name: bittorrent.{{ internal_domain }}
    fields:
      - name: host
        value: bittorrent.{{ internal_domain }}
      - name: urlBase
        value: ""
      - name: port
        value: 443
      - name: category
        value: movie-radarr
      - name: username
        value: admin
      - name: password
        value: "{{ bittorrent_webui_decoded_password }}"
      - name: useSsl
        value: true
    protocol: torrent
    config_contract: QBittorrentSettings
    implementation: QBittorrent
    tags: []
