---
# This workaround is needed because the current release of Bitwarden Secret Manager is bugged and
# two variables cannot be used at the same time.
# https://community.bitwarden.com/t/bitwarden-lookup-plugin-for-ansible-causes-panick-errors-and-a-worker-was-found-in-a-dead-state/64579/7
- name: Bitwarden workaround for p2p_radarr_api_key
  ansible.builtin.set_fact:
    p2p_radarr_api_key: "{{ p2p_radarr_api_key }}"

- name: Ensure root folder exists in Radarr
  devopsarr.radarr.radarr_root_folder:
    radarr_url: "{{ _p2p_radarr_server_url }}"
    radarr_api_key: "{{ p2p_radarr_api_key }}"
    path: "{{ p2p_radarr_container_data_dir }}"

- name: Ensure download client exists in Radarr
  devopsarr.radarr.radarr_download_client:
    radarr_url: "{{ _p2p_radarr_server_url }}"
    radarr_api_key: "{{ p2p_radarr_api_key }}"
    remove_completed_downloads: true
    remove_failed_downloads: true
    enable: true
    priority: 1
    name: bittorrent.{{ internal_domain }}
    fields:
      - name: host
        value: bittorrent.{{ internal_domain }}
      - name: urlBase
        value: ""
      - name: port
        value: 443
      - name: category
        value: movie-radarr
      - name: username
        value: admin
      - name: password
        value: "{{ bittorrent_webui_decoded_password }}"
      - name: useSsl
        value: true
    protocol: torrent
    config_contract: QBittorrentSettings
    implementation: QBittorrent
    tags: []

- name: Ensure custom format Not Italian exists
  devopsarr.radarr.radarr_custom_format:
    radarr_url: "{{ _p2p_radarr_server_url }}"
    radarr_api_key: "{{ p2p_radarr_api_key }}"
    include_custom_format_when_renaming: false
    name: "Language: Not Italian"
    specifications:
      - name: italian
        implementation: LanguageSpecification
        negate: true
        required: false
        fields:
          - name: value
            value: 5
  register: not_italian_custom_format

- name: Ensure quality profile High Quality - Italian exists
  devopsarr.radarr.radarr_quality_profile:
    radarr_url: "{{ _p2p_radarr_server_url }}"
    radarr_api_key: "{{ p2p_radarr_api_key }}"
    name: High Quality - Italian
    upgrade_allowed: true
    cutoff: 19
    min_format_score: 0
    cutoff_format_score: 0
    language:
      name: Any
      id: -1
    quality_groups:
      - qualities:
          - id: 9
            name: HDTV-1080p
            source: tv
            resolution: 1080
      - qualities:
          - id: 3
            name: WEBDL-1080p
            source: webdl
            resolution: 1080
      - qualities:
          - id: 15
            name: WEBRip-1080p
            source: webrip
            resolution: 1080
      - qualities:
          - id: 7
            name: Bluray-1080p
            source: bluray
            resolution: 1080
      - qualities:
          - id: 30
            name: Remux-1080p
            source: bluray
            resolution: 1080
      - qualities:
          - id: 16
            name: HDTV-2160p
            source: tv
            resolution: 2160
      - qualities:
          - id: 18
            name: WEBDL-2160p
            source: webdl
            resolution: 2160
      - qualities:
          - id: 17
            name: WEBRip-2160p
            source: webrip
            resolution: 2160
      - qualities:
          - id: 19
            name: Bluray-2160p
            source: bluray
            resolution: 2160
      - qualities:
          - id: 31
            name: Remux-2160p
            source: bluray
            resolution: 2160
      - qualities:
          - id: 22
            name: BR-DISK
            source: bluray
            resolution: 1080
      - qualities:
          - id: 10
            name: Raw-HD
            source: tv
            resolution: 1080
    formats:
      - id: "{{ not_italian_custom_format.id }}"
        name: "{{ not_italian_custom_format.name }}"
        score: -1000
