---
- name: Set server URLs
  ansible.builtin.set_fact:
    sonarr_fqdn: sonarr.{{ internal_domain }}
    sonarr_server_url: https://sonarr.{{ internal_domain }}
    _p2p_prowlarr_server_url: https://prowlarr.{{ internal_domain }}
    _p2p_radarr_fqdn: radarr.{{ internal_domain }}
    _p2p_radarr_server_url: https://radarr.{{ internal_domain }}
    overseerr_server_url: https://overseerr.{{ internal_domain }}

- name: Ensure group exists with name {{ media_shared_group }}
  ansible.builtin.group:
    name: "{{ media_shared_group }}"
    state: present
  register: media_group_result

- name: Set media_gid
  ansible.builtin.set_fact:
    media_gid: "{{ media_group_result.gid }}"

- name: Deploy qBittorrent
  ansible.builtin.import_tasks: deploy_bittorrent.yaml

- name: Deploy Bitmagnet
  ansible.builtin.import_tasks: deploy_bitmagnet.yaml

- name: Deploy Prowlarr
  ansible.builtin.import_tasks: deploy_prowlarr.yaml

- name: Deploy Sonarr
  ansible.builtin.import_tasks: deploy_sonarr.yaml

- name: Deploy Radarr
  ansible.builtin.import_tasks: deploy_radarr.yaml

- name: Deploy Overseerr
  ansible.builtin.import_tasks: deploy_overseerr.yaml

- name: Configure Sonarr
  ansible.builtin.import_tasks: configure_sonarr.yaml
  delegate_to: localhost
  become: false

- name: Configure Radarr
  ansible.builtin.import_tasks: configure_radarr.yaml
  delegate_to: localhost
  become: false

- name: Configure Prowlarr
  ansible.builtin.import_tasks: configure_prowlarr.yaml
  delegate_to: localhost
  become: false

- name: Configure Overseerr
  ansible.builtin.import_tasks: configure_overseerr.yaml
  delegate_to: localhost
  become: false
