---
- name: Reload systemd daemons
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Grafana service
  ansible.builtin.service:
    name: grafana.service
    state: restarted
