- name: Install Kea
  ansible.builtin.apt:
    name: isc-dhcp-server
    state: present
    update_cache: true

- name: Configure DHCP server interface
  ansible.builtin.lineinfile:
    path: /etc/default/isc-dhcp-server
    line: INTERFACESv4="{{ bridge_name }}"
    create: true
    regexp: ^INTERFACESv4=

- name: Network | Enable | Set DHCP facts
  ansible.builtin.set_fact:
    __network_dhcp_address: "{{ dhcp_primary if network_dhcp_role == 'primary' else dhcp_failover }}"
    __network_dhcp_peer_address: "{{ dhcp_failover if network_dhcp_role == 'primary' else dhcp_primary }}"

- name: Configure DHCP server
  ansible.builtin.template:
    # https://kb.isc.org/docs/aa-00502
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    mode: "0644"
    backup: true
  notify:
    - Restart DHCP service

- name: Enable DHCP service
  ansible.builtin.service:
    name: isc-dhcp-server
    enabled: true
    state: started

- name: Disable DHCP6 service
  ansible.builtin.service:
    name: isc-dhcp-server6
    enabled: false
    state: stopped
