apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-rwo-replicated
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: "thin-pool"
  linstor.csi.linbit.com/placementCount: "2"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: piraeus-rwx-shared
provisioner: linstor.csi.linbit.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  linstor.csi.linbit.com/storagePool: "thin-pool"
  linstor.csi.linbit.com/placementCount: "2"
