- name: Restart nftables service
  service:
    name: nftables
    state: restarted

- name: Restart NetworkManager service
  service:
    name: NetworkManager
    state: restarted

- name: Restart DHCP service
  service:
    name: isc-dhcp-server
    state: restarted