---
forgejo_namespace: git-system
forgejo_version: "17.1.0"
forgejo_domain: "git.{{ internal_domain }}"
forgejo_db_host: "forgejo-db-rw.cnpg-clusters.svc.cluster.local:5432"
forgejo_storage_class: "piraeus-rwo-replicated"
forgejo_ssh_domain: "git.{{ internal_domain }}"
forgejo_ssh_listen_port: 2222
forgejo_ssh_port: 2222
forgejo_admin_username: "forgejo_admin"
