# This workaround is needed because the current release of Bitwarden Secret Manager is bugged and
# two variables cannot be used at the same time.
# https://community.bitwarden.com/t/bitwarden-lookup-plugin-for-ansible-causes-panick-errors-and-a-worker-was-found-in-a-dead-state/64579/7
- name: Bitwarden workaround for internal_domain
  ansible.builtin.set_fact:
    internal_domain: "{{ internal_domain }}"

- name: Overseerr server url
  ansible.builtin.set_fact:
    overseerr_server_url: "https://overseerr.{{ internal_domain }}"

- name: Retrieve Sonarr settings from Overseerr
  ansible.builtin.uri:
    url: "{{ prowlarr_server_url }}/api/v1/settings/sonarr"
    method: GET
    headers:
      Accept: application/json
      X-Api-Key: "{{ overseerr_api_key }}"
    status_code: [200]
  register: overseerr_sonar_settings_api_response