- name: Deploy qBittorrent
  ansible.builtin.import_tasks: deploy_bittorrent.yaml

- name: Deploy Bitmagnet
  ansible.builtin.import_tasks: deploy_bitmagnet.yaml

- name: Deploy Prowlarr
  ansible.builtin.import_tasks: deploy_prowlarr.yaml

- name: Deploy Sonarr
  ansible.builtin.import_tasks: deploy_sonarr.yaml

- name: Configure Sonarr
  ansible.builtin.import_tasks: configure_sonarr.yaml
  delegate_to: localhost
  become: false

- name: Configure Prowlarr
  ansible.builtin.import_tasks: configure_prowlarr.yaml
  delegate_to: localhost
  become: false
