# This workaround is needed because the current release of Bitwarden Secret Manager is bugged and
# two variables cannot be used at the same time.
# https://community.bitwarden.com/t/bitwarden-lookup-plugin-for-ansible-causes-panick-errors-and-a-worker-was-found-in-a-dead-state/64579/7
- name: Bitwarden workaround for internal_domain
  ansible.builtin.set_fact:
    internal_domain: "{{ internal_domain }}"

- name: Set server URLs
  ansible.builtin.set_fact:
    prowlarr_server_url: "https://prowlarr.{{ internal_domain }}"
    sonarr_fqdn: "sonarr.{{ internal_domain }}"
    sonarr_server_url: "https://sonarr.{{ internal_domain }}"
    overseerr_server_url: "https://overseerr.{{ internal_domain }}"

- name: Ensure group exists with name {{ media_shared_group }}
  ansible.builtin.group:
    name: "{{ media_shared_group }}"
    state: present
  register: media_group_result

- name: Set media_gid
  ansible.builtin.set_fact:
    media_gid: "{{ media_group_result.gid }}"

- name: Deploy qBittorrent
  ansible.builtin.import_tasks: deploy_bittorrent.yaml

- name: Deploy Bitmagnet
  ansible.builtin.import_tasks: deploy_bitmagnet.yaml

- name: Deploy Prowlarr
  ansible.builtin.import_tasks: deploy_prowlarr.yaml

- name: Deploy Sonarr
  ansible.builtin.import_tasks: deploy_sonarr.yaml

- name: Deploy Overseerr
  ansible.builtin.import_tasks: deploy_overseerr.yaml

- name: Configure Sonarr
  ansible.builtin.import_tasks: configure_sonarr.yaml
  delegate_to: localhost
  become: false

- name: Configure Prowlarr
  ansible.builtin.import_tasks: configure_prowlarr.yaml
  delegate_to: localhost
  become: false

- name: Configure Overseerr
  ansible.builtin.import_tasks: configure_overseerr.yaml
  delegate_to: localhost
  become: false
