- name: Deploy qBittorrent
  ansible.builtin.import_tasks: deploy_bittorrent.yaml

- name: Deploy Bitmagnet
  ansible.builtin.import_tasks: deploy_bitmagnet.yaml

- name: Deploy Prowlarr
  ansible.builtin.import_tasks: deploy_prowlarr.yaml


- name: Deploy Sonarr
  ansible.builtin.import_tasks: deploy_sonarr.yaml
