---
home:
  vars:
    secret_bundle: "{{ lookup('community.general.bitwarden_secrets_manager', '22bdfa7d-f452-4a62-85d3-b40c0095369a').value }}"
    ##### Required for first setup #####
    internal_network: 172.16.0.0
    internal_network_netmask_length: 16
    internal_network_netmask: 255.255.0.0
    internal_gateway: 172.16.255.254
    internal_network_dhcp_start: 172.16.200.0
    internal_network_dhcp_end: 172.16.200.254
    network_gateway_virtual_ip: 172.16.255.254
    k8s_cp_network: 172.20.0.0
    k8s_cp_netmask: 16
    k8s_lb_network: 172.16.184.0/24
    k8s_ingress_lb_ip: "172.16.184.10"
    # Provide only the sub-domain prefix. They will be suffixed with .{{ internal_domain }}
    k8s_public_domains: [""]
    k8s_internal_domains: ["git"]
    network_dyn_dns_entry: "ingress"
    ##### END Required for first setup #####
    ##### Deployment preferences defaults to false for safety #####
    deploy_grafana: false
    deploy_prometheus: false
    deploy_alertmanager: false
    deploy_mediastack: false
    deploy_logging: false
    deploy_home_assistant: false
    deploy_coder: false
    deploy_mqtt: false
    deploy_idp: false
    deploy_netbird: false
    deploy_adguard: false
    deploy_forgejo: true
    deploy_nut: false
    # Kubernetes Netbird Configuration
    k8s_netbird_deploy_exit_node: true
    k8s_netbird_deploy_jump_node: true
    k8s_netbird_deploy_dashboard: true

    idp_dynamic_apps:
      - name: forgejo
        redirect_uris:
          - "https://git.{{ internal_domain }}/user/oauth2/Zitadel/callback"
        app_type: "OIDC_APP_TYPE_WEB"
        auth_method_type: "OIDC_AUTH_METHOD_TYPE_BASIC"
    #### Shared deployment variables #####
    linstor_volume_group: linstor_vg
    linstor_thin_pool: thin_pool
  hosts:
    node1:
      ansible_host: 172.16.255.251
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_ssh_args: -o ControlMaster=auto -o ControlPersist=120s
      ##### Required for first setup #####
      network_is_router: true
      #wan_interface: br0
      internal_interface: enp4s0
      #physical_interface: enp4s0
      internal_ip: 172.16.255.251
      network_gateway_role: secondary
      network_k8s_ip: 172.20.0.1
      network_dhcp_role: secondary
      deploy_adguard: false
      system_update_day: "never"
      ##### END Required for first setup #####
      #### deployment preferences
      deploy_grafana: false
      deploy_prometheus: false
      deploy_alertmanager: false
      deploy_mediastack: false
      deploy_logging: false
      deploy_home_assistant: false
      deploy_coder: false
      deploy_mqtt: false
      deploy_idp: false
      deploy_netbird: true
      deploy_pinchflat: false
      ##### ad hoc deployments variables #####
      vpn_deploy_exit_node: true
      vpn_deploy_jump_node: true
      vpn_deploy_management_server: false
      vpn_deploy_dashboard: false
      vpn_deploy_stun_server: true
      vpn_deploy_protonvpn: true
      vpn_deploy_relay_server: true
      auto_ansible_hour_schedule: "1"
      zigbee_usb_device: /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03318564-if00-port0
      p2p_deploy_bitmagnet: false
      ##### Storage Configuration (Piraeus / Linstor) #####
      linstor_node_enabled: true
      linstor_use_loopback: true
      linstor_backing_file_size_mb: 51200
      linstor_backing_file_path: /var/local/piraeus/linstor-backing.img
      linstor_loop_device: /dev/loop100


    node2:
      ansible_host: 172.16.255.252
      ##### Required for first setup #####
      network_is_router: true
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_ssh_args: -o ControlMaster=auto -o ControlPersist=120s
      internal_interface: enp1s0
      internal_ip: 172.16.255.252
      network_k8s_ip: 172.20.0.2
      network_gateway_role: primary
      network_dhcp_role: primary
      deploy_adguard: true
      system_update_day: "never"
      ##### END Required for first setup #####
      #### deployment preferences
      deploy_grafana: true
      deploy_prometheus: true
      deploy_alertmanager: true
      deploy_mediastack: true
      deploy_logging: true
      deploy_home_assistant: true
      deploy_coder: true
      deploy_mqtt: true
      deploy_idp: true
      deploy_netbird: true
      deploy_pinchflat: true
      deploy_nut: true
      ##### ad hoc deployments variables #####
      vpn_deploy_exit_node: true
      vpn_deploy_jump_node: true
      vpn_deploy_management_server: true
      vpn_deploy_dashboard: false
      vpn_deploy_stun_server: true
      vpn_deploy_protonvpn: true
      vpn_deploy_relay_server: true
      auto_ansible_hour_schedule: "3"
      zigbee_usb_device: /dev/serial/by-id/usb-dresden_elektronik_ConBee_III_DE03318564-if00-port0
      p2p_deploy_bitmagnet: true
      logging_enable_aws_cloudwatch: false
      ##### Storage Configuration (Piraeus / Linstor) #####
      linstor_node_enabled: true
      linstor_use_loopback: true
      linstor_backing_file_size_mb: 51200
      linstor_backing_file_path: /app/piraeus/linstor-backing.img
      linstor_loop_device: /dev/loop100


    node3:
      ansible_host: 172.16.255.253
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/ansible
      ansible_ssh_args: -o ControlMaster=auto -o ControlPersist=120s
      ##### Required for first setup #####
      network_is_router: true
      network_k8s_ip: 172.20.0.3
      internal_interface: enp1s0
      internal_ip: 172.16.255.253
      deploy_adguard: true
      system_update_day: "never"
      ##### Required for first setup #####
      ##### Deployment preferences #####
      deploy_grafana: false
      deploy_prometheus: false
      deploy_alertmanager: false
      deploy_mediastack: false
      deploy_logging: true
      deploy_home_assistant: false
      deploy_coder: false
      deploy_mqtt: false
      deploy_idp: false
      deploy_netbird: true
      # Ad hoc deployments variables #####
      vpn_deploy_exit_node: true
      vpn_deploy_jump_node: true
      vpn_deploy_management_server: false
      vpn_deploy_dashboard: false
      vpn_deploy_stun_server: false
      vpn_deploy_protonvpn: false
      vpn_deploy_relay_server: false
      auto_ansible_hour_schedule: "23"
      logging_enable_aws_cloudwatch: false
      ##### Storage Configuration (Piraeus / Linstor) #####
      linstor_node_enabled: true
      linstor_use_loopback: true
      linstor_backing_file_size_mb: 51200
      linstor_backing_file_path: /var/local/piraeus/linstor-backing.img
      linstor_loop_device: /dev/loop100


kube_control_plane:
  hosts:
    node1:
    node2:
    node3:

kube_node:
  hosts:
    node1:
    node2:
    node3:

etcd:
  hosts:
    node1:
    node2:
    node3:

k8s_cluster:
  children:
    kube_control_plane:
    kube_node:
