---
- name: Reload systemd daemons for media-server role
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart plex network
  ansible.builtin.systemd_service:
    state: restarted
    name: plex-network

- name: Restart plex service
  ansible.builtin.systemd_service:
    state: restarted
    name: plex
