---
# Prometheus and AlertManager run as nobody:nogroup

- name: Create /app/prometheus/work directory
  ansible.builtin.file:
    path: /app/prometheus/work
    state: directory
    mode: "0770"
    owner: root
    group: nogroup

- name: Create config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: root
    group: nogroup
  with_items:
    - /app/prometheus/conf
    - /app/prometheus/conf/rules
    - /app/alertmanager/conf

- name: Copy prometheus.yaml configuration
  ansible.builtin.copy:
    content: |
      global:

      scrape_configs:
        - job_name: 'prometheus'
          scrape_interval: 15s
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'homelab-01'
          scrape_interval: 10s
          static_configs:
            - targets: ['{{ internal_gateway }}:9100']

        - job_name: 'pingexporter'
          scrape_interval: 1s
          scheme: https
          static_configs:
            - targets: ['pingexporter.{{ internal_domain }}']

        - job_name: 'idp'
          scrape_interval: 1s
          scheme: https
          metrics_path: "/debug/metrics"
          static_configs:
            - targets: ['idp.{{ internal_domain }}']

      rule_files:
        - /opt/prometheus/conf/rules/*.yaml

      alerting:
        alertmanagers:
          - scheme: https
            static_configs:
              - targets: ['alertmanager.{{ internal_domain }}']

    dest: /app/prometheus/conf/prometheus.yaml
    mode: "0640"
    owner: root
    group: nogroup
  notify: Restart Prometheus service

- name: Copy system rules
  ansible.builtin.template:
    src: system-alert-rules.yaml.j2
    dest: /app/prometheus/conf/rules/system.yaml
    mode: "0640"
    owner: root
    group: nogroup
  notify: Restart Prometheus service

- name: Copy alertmanager.yaml configuration
  ansible.builtin.copy:
    content: |
      global:
        smtp_from: {{ alertmanager_sender }}
        smtp_smarthost: smtp.sendgrid.net:587
        smtp_auth_username: apikey
        smtp_auth_password: {{ alertmanager_smtp_auth_password }}
      route:
        receiver: 'me'

      receivers:
        - name: 'me'
          email_configs:
            - to: '{{ alertmanager_receiver_email }}'
              send_resolved: true

    dest: /app/alertmanager/conf/alertmanager.yaml
    mode: "0640"
    owner: root
    group: nogroup
  notify: Restart AlertManager service

- name: Create prometheus.service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Podman container-prometheus.service
      Documentation=man:podman-generate-systemd(1)
      Wants=network-online.target
      After=network-online.target
      RequiresMountsFor=%t/containers

      [Service]
      Environment=PODMAN_SYSTEMD_UNIT=%n
      Restart=on-failure
      TimeoutStopSec=70
      ExecStart=/usr/bin/podman run \
              --cidfile=%t/%n.ctr-id \
              --cgroups=no-conmon \
              --rm \
              --sdnotify=conmon \
              --replace \
              -d \
              --name prometheus \
              -v /app/prometheus/work:/opt/prometheus/work \
              -v /app/prometheus/conf:/opt/prometheus/conf:ro \
              --label="traefik.enable=true" \
              --label="traefik.http.routers.prometheus.rule=Host(`prometheus.{{ internal_domain }}`)" \
              --label="traefik.http.routers.prometheus.entrypoints=websecure" \
              --label="traefik.http.routers.prometheus.tls.certresolver=letsencrypt" \
              --label="traefik.http.routers.prometheus.tls.domains[0].main=prometheus.{{ internal_domain }}" \
              --label="traefik.http.services.prometheus.loadbalancer.server.port=9090" \
              --dns=172.16.255.254 \
              docker.io/prom/prometheus:v2.52.0 \
              --config.file=/opt/prometheus/conf/prometheus.yaml \
              --storage.tsdb.path=/opt/prometheus/work \
              --storage.tsdb.retention.size="10GB" \
              --web.external-url=https://prometheus.{{ internal_domain }}/
      ExecStop=/usr/bin/podman stop \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      ExecStopPost=/usr/bin/podman rm \
              -f \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      Type=notify
      NotifyAccess=all

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"
  notify:
    - Reload systemd daemons
    - Restart Prometheus service

- name: Create alertmanager.service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Podman container-alertmanager.service
      Documentation=man:podman-generate-systemd(1)
      Wants=network-online.target
      After=network-online.target
      RequiresMountsFor=%t/containers

      [Service]
      Environment=PODMAN_SYSTEMD_UNIT=%n
      Restart=on-failure
      TimeoutStopSec=70
      ExecStart=/usr/bin/podman run \
              --cidfile=%t/%n.ctr-id \
              --cgroups=no-conmon \
              --rm \
              --sdnotify=conmon \
              --replace \
              -d \
              --name alertmanager \
              -v /app/alertmanager/conf:/opt/alertmanager/conf:ro \
              --label="traefik.enable=true" \
              --label="traefik.http.routers.alertmanager.rule=Host(`alertmanager.{{ internal_domain }}`)" \
              --label="traefik.http.routers.alertmanager.entrypoints=websecure" \
              --label="traefik.http.routers.alertmanager.tls.certresolver=letsencrypt" \
              --label="traefik.http.routers.alertmanager.tls.domains[0].main=alertmanager.{{ internal_domain }}" \
              --label="traefik.http.services.alertmanager.loadbalancer.server.port=9093" \
              --dns=172.16.255.254 \
              quay.io/prometheus/alertmanager:v0.27.0 \
              --config.file=/opt/alertmanager/conf/alertmanager.yaml \
              --log.level=debug \
              --web.external-url=https://alertmanager.{{ internal_domain }}/
      ExecStop=/usr/bin/podman stop \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      ExecStopPost=/usr/bin/podman rm \
              -f \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      Type=notify
      NotifyAccess=all

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/alertmanager.service
    mode: "0644"
  notify:
    - Reload systemd daemons
    - Restart AlertManager service

- name: Enable and start services
  ansible.builtin.systemd_service:
    name: "{{ item }}.service"
    enabled: true
    state: started
  with_items:
    - prometheus
    - alertmanager
