- name: Check required variables
  fail:
    msg: "The variables 'wan_interface' and 'internal_interface' are required."
  when: "wan_interface == '' or internal_interface == ''"

- name: Install iproute2
  apt:
    name: iproute2
    state: present
    update_cache: yes

# Enable IP forwarding
- name: Configure routing table
  copy:
    content: |
      net.ipv4.ip_forward=1
    dest: /etc/sysctl.d/20-ip-forward.conf
    mode: 0644

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    state: present
