- name: Create /app/traefik/conf directory
  file:
    path: /app/traefik/conf
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Copy traefik.yaml configuration
  copy:
    content: |
      global:
        checkNewVersion: true
        sendAnonymousUsage: false

      entryPoints:
        web:
          address: :80

        websecure:
          address: :443

      api:
        # Dashboard is server on port 8080
        insecure: true
        dashboard: true

      providers:
        docker:
          exposedByDefault: false
          # This is a security risk, it should be better
          # to expose and use a TCP socket
          endpoint: "unix:///var/run/docker.sock"

      log:
        level: INFO

    dest: /app/traefik/conf/traefik.yaml
    mode: 0600
    owner: root
    group: root
  notify: Restart Traefik service

- name: Create traefik.service file
  copy:
    content: |
      [Unit]
      Description=Podman container-traefik.service
      Documentation=man:podman-generate-systemd(1)
      Wants=network-online.target
      After=network-online.target
      RequiresMountsFor=%t/containers

      [Service]
      Environment=PODMAN_SYSTEMD_UNIT=%n
      Restart=on-failure
      TimeoutStopSec=70
      ExecStart=/usr/bin/podman run \
              --cidfile=%t/%n.ctr-id \
              --cgroups=no-conmon \
              --rm \
              --sdnotify=conmon \
              --replace \
              -d \
              --name traefik \
              -v /app/traefik/conf/traefik.yaml:/etc/traefik/traefik.yml:ro \
              -v /var/run/docker.sock:/var/run/docker.sock:ro \
              -p 172.16.255.254:80:80/tcp \
              -p 172.16.255.254:8080:8080/tcp \
              -p 172.16.255.254:443:443/udp \
              docker.io/traefik:v3.0.3
      ExecStop=/usr/bin/podman stop \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      ExecStopPost=/usr/bin/podman rm \
              -f \
              --ignore -t 10 \
              --cidfile=%t/%n.ctr-id
      Type=notify
      NotifyAccess=all

      [Install]
      WantedBy=default.target
    dest: /etc/systemd/system/traefik.service
    mode: 0644
  register: traefik_service_unit

- name: Reload systemd daemons
  systemd_service:
    daemon_reload: yes
  when: traefik_service_unit.changed

- name: Enable and start traefik service
  systemd_service:
    name: traefik.service
    enabled: yes
    state: started
