---
k8s_coder_namespace: coder
k8s_coder_workspaces_namespace: coder-workspaces
# Available versions https://github.com/coder/coder/pkgs/container/coder
coder_version: v2.35.4
k8s_coder_replicas: 1

coder_db_host: "coder-db-rw.cnpg-clusters.svc"
coder_db_port: "5432"
coder_db_name: coder-db
coder_db_user: coder

coder_service_port: 7080
coder_external_domain: "coder.{{ internal_domain }}"
