---
- name: Reload systemd daemons
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart Prometheus service
  ansible.builtin.service:
    name: prometheus.service
    state: restarted

- name: Restart AlertManager service
  ansible.builtin.service:
    name: alertmanager.service
    state: restarted
