- name: Reload systemd daemons
  systemd_service:
    daemon_reload: yes

- name: Restart Prometheus service
  service:
    name: prometheus.service
    state: restarted

- name: Restart AlertManager service
  service:
    name: alertmanager.service
    state: restarted