- name: Reload systemd daemons
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart bitmagnet network
  ansible.builtin.systemd_service:
    state: restarted
    name: bitmagnet-network

- name: Restart bitmagnet DB service
  ansible.builtin.systemd_service:
    state: restarted
    name: bitmagnet-db

- name: Restart bitmagnet service
  ansible.builtin.systemd_service:
    state: restarted
    name: bitmagnet
