bitmagnet_version: v0.9.4
bitmagnet_conf_dir: /app/bitmagnet/conf
bitmagnet_work_dir: /app/bitmagnet/work
prowlarr_version: 1.20.1
prowlarr_conf_dir: /app/prowlarr/conf
prowlarr_work_dir: /app/prowlarr/work
bittorrent_version: 4.6.5-r0-ls341
bittorrent_port: 53428
bittorrent_work_dir: /app/bittorrent/work
sonarr_version: 4.0.7
sonarr_conf_dir: /app/sonarr/conf
sonarr_work_dir: /app/sonarr/work
overseerr_version: 14cf43de26e44d5ef082806c2b97a88ce4bd6c84
overseerr_conf_dir: /app/overseerr/conf
overseerr_work_dir: /app/overseerr/work
