- name: Get all directories in {{ coder_template_src_dir }}
  find:
    paths: "{{ coder_template_src_dir }}"
    patterns: '*'
    depth: 1
    file_type: directory
    excludes: '.,..'
  register: templates_find_result

- name: Get user organization ID
  uri:
    url: "{{ coder_server_url }}/api/v2/users/me/organizations"
    method: GET
    headers:
      Coder-Session-Token: "{{ coder_api_token }}"
      Accept: application/json
  register: user_organization_id_result

- include_tasks: consolidate-template.yaml
  loop: "{{ templates_find_result.files }}"
  vars:
    template_dir: "{{ item.path }}"
    template_name: "{{ item.path | basename }}"
    # Assume that user has only one organization
    organization_id: "{{ user_organization_id_result.json[0].id }}"
