---
- name: Wait for Home Assistant to be ready
  ansible.builtin.uri:
    url: "{{ home_assistant_internal_url }}/api/"
    method: GET
    timeout: 10
    status_code: [200, 401, 403]
  register: home_assistant_health_check
  until: home_assistant_health_check.status == 200 or home_assistant_health_check.status == 401 or home_assistant_health_check.status == 403
  retries: 30
  delay: 10

- name: Check if Home Assistant is configured
  ansible.builtin.uri:
    url: "{{ home_assistant_internal_url }}/api/config"
    method: GET
    timeout: 10
    status_code: [200, 401, 403]
  register: home_assistant_config_check

- name: Display Home Assistant setup info
  ansible.builtin.debug:
    msg: |
      Home Assistant is ready at {{ home_assistant_internal_url }}
      {% if home_assistant_config_check.status == 401 %}
      Please complete the initial setup by visiting the web interface.
      After setup, you can configure Zitadel integration through the UI:
      1. Go to Settings > People > Users
      2. Add a new user integration
      3. Configure trusted proxies if needed
      {% else %}
      Home Assistant appears to be already configured.
      {% endif %}
