---
- name: Reload systemd daemons for idp role
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart zitadel network
  ansible.builtin.systemd_service:
    state: restarted
    name: zitadel-network

- name: Restart zitadel database service
  ansible.builtin.systemd_service:
    state: restarted
    name: zitadel-db

- name: Restart zitadel service
  ansible.builtin.systemd_service:
    state: restarted
    name: zitadel
