- name: Create /etc/systemd/resolved.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: "0755"

- name: Disable DNSStubListener
  ansible.builtin.copy:
    content: |
      [Resolve]
      DNSStubListener=no
    dest: /etc/systemd/resolved.conf.d/noresolved.conf
    mode: "0644"
  register: noresolved_conf_file

- name: Create configuration file for DNS internal domain
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: "/etc/systemd/resolved.conf.d/{{internal_domain}}.conf"
    mode: "0644"
  notify:
  register: internal_resolved_conf_file

- name: Restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  when: noresolved_conf_file.changed or internal_resolved_conf_file.changed