---
- name: Get internal interface IP address
  ansible.builtin.set_fact:
    internal_interface_ip: "{{ ansible_facts[internal_interface]['ipv4']['address'] }}"

- name: Create sshd_config.d file for internal interface
  ansible.builtin.copy:
    dest: /etc/ssh/sshd_config.d/99-hardening.conf
    backup: true
    mode: "0644"
    owner: root
    group: root
    content: |
      ListenAddress {{ internal_interface_ip }}
      PermitRootLogin no
      PubkeyAuthentication yes
      # Max retries per connection, if you disconnect and reconnect the value is reset
      MaxAuthTries 3
      # Max time to complete a connection
      LoginGraceTime 20
      PermitEmptyPasswords no
      # Allow all users from the internal network and podman networks
      AllowUsers *@{{ (internal_network + '/' + internal_network_netmask) | ansible.utils.ipaddr('network/prefix') }} *@10.0.0.0/8
      # Not used in this specific Environment
      ChallengeResponseAuthentication no
      PasswordAuthentication no
      KerberosAuthentication no
      GSSAPIAuthentication no
      X11Forwarding no
      AllowAgentForwarding no
      # https://man.openbsd.org/sshd_config#AllowTcpForwarding
      # Since we have shell access there is no point in disabling it
      AllowTcpForwarding local
      PermitTunnel no
