---
- name: Pre-tasks for Kubernetes installation
  hosts: all

  pre_tasks:
    - ansible.builtin.import_role:
        name: homelab.utils.render_variables
      tags:
        - always

- name: Prepare custom etcd data directory
  hosts: etcd
  become: yes

  tasks:
    - name: Ensure the custom etcd directory exists
      file:
        path: "{{ etcd_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0700"

- name: Prepare custom containerd and kubelet directories
  hosts: k8s_cluster
  become: yes

  tasks:
    - name: Ensure custom containerd storage directory exists
      file:
        path: "{{ containerd_storage_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0711"

    - name: Ensure custom kubelet mount source directory exists
      ansible.builtin.file:
        path: "{{ kubelet_mount_src }}"
        state: directory
        owner: root
        group: root
        mode: "0750"
      when: kubelet_mount_src is defined

    - name: Ensure default /var/lib/kubelet directory exists
      ansible.builtin.file:
        path: "/var/lib/kubelet"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Mount custom directory to /var/lib/kubelet via fstab
      ansible.posix.mount:
        path: /var/lib/kubelet
        src: "{{ kubelet_mount_src }}"
        fstype: "{{ kubelet_mount_fstype | default('none') }}"
        opts: "{{ kubelet_mount_opts | default('defaults,bind') }}"
        state: mounted
      register: kubelet_mount
      when: kubelet_mount_src is defined

    - name: Reload systemd daemon to recognize fstab changes
      ansible.builtin.systemd:
        daemon_reload: yes
      when:
        - kubelet_mount_src is defined
        - kubelet_mount.changed


- name: Install Kubernetes
  when: k8s_node_bootstrapped is defined and not k8s_node_bootstrapped
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.cluster
  vars:
    maximal_ansible_version: 2.19.0 # Force check on ansible version to avoid downgrading
    ip: "{{ network_k8s_ip }}"
    access_ip: "{{ network_k8s_ip }}"
  tags: k8s

- name: Update Kubernetes
  when: k8s_node_bootstrapped is defined and k8s_node_bootstrapped
  ansible.builtin.import_playbook: kubernetes_sigs.kubespray.upgrade_cluster
  vars:
    maximal_ansible_version: 2.19.0
    ip: "{{ network_k8s_ip }}"
    access_ip: "{{ network_k8s_ip }}"
  tags: k8s

- name: Customize K8s control plane networking
  hosts: kube_control_plane
  become: yes

  tasks:
    - name: Kubernetes | Deploy CiliumL2AnnouncementPolicy policy
      run_once: true
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: "cilium.io/v2alpha1"
          kind: CiliumL2AnnouncementPolicy
          metadata:
            name: default
          spec:
            interfaces:
              - k8s-cp
            loadBalancerIPs: true

- name: Deploy Kubernetes Ingress
  hosts: kube_control_plane
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: homelab.system.k8s_ingress
      tags: k8s-ingress

- name: Deploy Piraeus K8s-Native Storage Solution
  hosts: kube_control_plane
  become: yes

  tasks:
    - ansible.builtin.import_role:
        name: homelab.system.k8s_piraeus
      tags: k8s-storage

- name: Deploy CloudNativePG
  hosts: kube_control_plane
  become: yes

  tasks:
    - name: Deploy CloudNativePG Clusters (System/App Namespace)
      ansible.builtin.import_role:
        name: homelab.system.k8s_db
      tags: k8s-db
      vars:
        k8s_db_clusters:
          - name: forgejo-db
            storage_size: "10Gi"
            username: "forgejouser"
            password: "{{ forgejo_db_password }}"
          - name: coder-db
            storage_size: "10Gi"
            username: "coder"
            password: "{{ coder_db_password }}"

    - name: Deploy CloudNativePG Clusters (Zitadel Namespace)
      ansible.builtin.import_role:
        name: homelab.system.k8s_db
      tags: k8s-db
      vars:
        k8s_db_cluster_namespace: zitadel
        k8s_db_clusters:
          - name: zitadeldb
            storage_size: "10Gi"
            username: "zitadeladmin"
            password: "{{ idp_zitadel_db_admin_password }}"
            priority_class_name: "critical-infra"
            resources:
              requests:
                cpu: "1000m"
                memory: "1Gi"
              limits:
                cpu: "1000m"
                memory: "1Gi"


- name: Deploy Forgejo
  hosts: kube_control_plane
  become: yes
  tasks:
    - ansible.builtin.import_role:
        name: homelab.apps.forgejo
      when: deploy_forgejo | default(false)
  tags: k8s-git

- name: Deploy Headlamp
  hosts: kube_control_plane
  become: yes
  tasks:
    - name: Headlamp | Find IDP host
      ansible.builtin.set_fact:
        headlamp_idp_host: "{{ item }}"
      loop: "{{ groups['all'] }}"
      when: hostvars[item].deploy_idp | default(false)
      run_once: true

    - name: Headlamp | Get Zitadel Terraform outputs
      command: terraform output -json
      args:
        chdir: /app/zitadel/conf/terraform
      register: zitadel_tf_output
      changed_when: false
      delegate_to: "{{ headlamp_idp_host }}"
      run_once: true
      become: true
      environment:
        AWS_ACCESS_KEY_ID: "{{ idp_terraform_state_access }}"
        AWS_SECRET_ACCESS_KEY: "{{ idp_terraform_state_secret }}"
      when: headlamp_idp_host is defined

    - name: Headlamp | Set Zitadel client credentials facts
      ansible.builtin.set_fact:
        headlamp_zitadel_client_id: "{{ (zitadel_tf_output.stdout | from_json).headlamp_client_id.value }}"
        headlamp_zitadel_client_secret: "{{ (zitadel_tf_output.stdout | from_json).headlamp_client_secret.value }}"
      run_once: true
      when: headlamp_idp_host is defined

    - ansible.builtin.import_role:
        name: homelab.apps.headlamp
      when: deploy_headlamp | default(false)
  tags: k8s-headlamp

- name: Deploy Coder
  hosts: kube_control_plane
  become: yes
  tasks:
    - ansible.builtin.import_role:
        name: homelab.apps.k8s_coder
      when: (deploy_coder | default(false) | bool) and (coder_deployment_type | default('podman') == 'k8s')
  tags: k8s-coder
