---
idp_config_external_domain: "idp.{{ internal_domain }}"
idp_config_external_port: "443"
idp_config_namespace: zitadel
idp_config_terraform_dir: "/app/zitadel/conf/terraform"

# Terraform state backend configuration
idp_terraform_state_s3_type: "other" # [aws, other]
idp_terraform_state_bucket: "homelab-terraform-state"


