---
- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present

- name: Set shell for users
  ansible.builtin.include_tasks: set-shell.yaml
  loop: "{{ base_ohmyzsh_users }}"

- name: Install omz
  ansible.builtin.include_tasks: install-omz.yaml
  loop: "{{ base_ohmyzsh_users }}"
