# This workaround is needed because the current release of Bitwarden Secret Manager is bugged and
# two variables cannot be used at the same time.
# https://community.bitwarden.com/t/bitwarden-lookup-plugin-for-ansible-causes-panick-errors-and-a-worker-was-found-in-a-dead-state/64579/7
- name: Bitwarden workaround for internal_domain
  ansible.builtin.set_fact:
    internal_domain: "{{ internal_domain }}"

- name: Deploy Zitadel
  ansible.builtin.import_tasks: deploy_zitadel.yaml
