- name: Install Terraform
  ansible.builtin.import_tasks: install_terraform.yaml

- name: Deploy Zitadel
  ansible.builtin.import_tasks: deploy_zitadel.yaml

- name: Configure Zitadel
  ansible.builtin.import_tasks: configure_zitadel.yaml
