---
- name: Reload systemd daemons for CrowdSec
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart CrowdSec service
  ansible.builtin.systemd_service:
    name: crowdsec.service
    state: restarted
  when: __crowdsec_any_enabled | bool

- name: Restart CrowdSec network
  ansible.builtin.systemd_service:
    name: "{{ crowdsec_network_name }}-network"
    state: restarted
  when: __crowdsec_any_enabled | bool
