---
- name: Reload systemd daemons for p2p role
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart bitmagnet network
  ansible.builtin.systemd_service:
    state: restarted
    name: bitmagnet-network

- name: Restart bitmagnet DB service
  ansible.builtin.systemd_service:
    state: restarted
    name: bitmagnet-db

- name: Restart bitmagnet service
  ansible.builtin.systemd_service:
    state: restarted
    name: bitmagnet

- name: Restart flaresolverr network
  ansible.builtin.systemd_service:
    state: restarted
    name: flaresolverr-network

- name: Restart flaresolverr service
  ansible.builtin.systemd_service:
    state: restarted
    name: flaresolverr

- name: Restart prowlarr network
  ansible.builtin.systemd_service:
    state: restarted
    name: prowlarr-network

- name: Restart prowlarr DB service
  ansible.builtin.systemd_service:
    state: restarted
    name: prowlarr-db

- name: Restart prowlarr service
  ansible.builtin.systemd_service:
    state: restarted
    name: prowlarr

- name: Restart bittorrent network
  ansible.builtin.systemd_service:
    state: restarted
    name: bittorrent-network

- name: Restart bittorrent service
  ansible.builtin.systemd_service:
    state: restarted
    name: bittorrent

- name: Restart sonarr network
  ansible.builtin.systemd_service:
    state: restarted
    name: sonarr-network

- name: Restart sonarr DB service
  ansible.builtin.systemd_service:
    state: restarted
    name: sonarr-db

- name: Restart sonarr service
  ansible.builtin.systemd_service:
    state: restarted
    name: sonarr

- name: Restart radarr network
  ansible.builtin.systemd_service:
    state: restarted
    name: radarr-network

- name: Restart radarr DB service
  ansible.builtin.systemd_service:
    state: restarted
    name: radarr-db

- name: Restart radarr service
  ansible.builtin.systemd_service:
    state: restarted
    name: radarr

- name: Restart overseerr network
  ansible.builtin.systemd_service:
    state: restarted
    name: overseerr-network

- name: Restart overseerr service
  ansible.builtin.systemd_service:
    state: restarted
    name: overseerr
