---
- name: Configure home lab
  hosts: all

  vars:
    # This group will be used to grant read access to media files between different applications
    media_shared_group: "media"
    # The directory is used to save finished media that can be served
    media_data_dir: "/external/media"

  pre_tasks:
    - name: Ensure group exists with name {{ media_shared_group }}
      ansible.builtin.group:
        name: "{{ media_shared_group }}"
        state: present
      register: media_group_result

    - name: Set media_gid
      ansible.builtin.set_fact:
        media_gid: "{{ media_group_result.gid }}"

    - name: Create directory {{ media_data_dir }}
      ansible.builtin.file:
        path: "{{ media_data_dir }}"
        state: directory
        mode: "0770"
        group: "{{ media_shared_group }}"

  roles:
    - role: roles/system/network
      become: true
      tags: "system-network"

    - role: roles/system/base
      become: true
      ohmyzsh_install: true
      ohmyzsh_users:
        - root
        - gbaratta
      tags: "system-base"

    - role: roles/system/ingress
      become: true
      tags: "ingress"

    - role: roles/system/containers
      become: true
      container_storage_dir: "/app/containers"
      tags: "containers"

    - role: roles/system/latency_monitor
      become: true
      tags: "monitoring"

    - role: roles/apps/adguard
      become: true
      tags: "adguard"

    - role: roles/apps/prometheus
      become: true
      tags: "prometheus"

    - role: prometheus.prometheus.node_exporter
      become: true
      node_exporter_web_listen_address: "172.16.255.254:9100"
      tags: "prometheus"

    - role: roles/apps/grafana
      become: true
      tags: "grafana"

    - role: roles/apps/coder
      become: true
      tags: "coder"

    - role: roles/apps/media-server
      plex_media_dir: "{{ media_data_dir }}"
      become: true
      tags: "media-server"

    - role: roles/apps/p2p
      # The directory is used to stage downloaded and incomplete files
      p2p_downloads_dir: "/external/torrent/downloads"
      sonarr_data_dir: "{{ media_data_dir }}/tv"
      become: true
      tags: "p2p"
