---
- hosts: all

  roles:
    - role: roles/system/network
      become: true
      tags: "system-network"

    - role: roles/system/base
      become: true
      ohmyzsh_install: true
      ohmyzsh_users:
        - root
        - gbaratta
      tags: "system-base"

    - role: roles/system/ingress
      become: true
      tags: "ingress"

    - role: roles/system/containers
      become: true
      container_storage_dir: "/app/containers"
      tags: "containers"

    - role: roles/apps/adguard
      become: true
      tags: "adguard"

    - role: roles/apps/prometheus
      become: true
      tags: "prometheus"

    - role: prometheus.prometheus.node_exporter
      become: true
      node_exporter_web_listen_address: "172.16.255.254:9100"

    - role: roles/apps/grafana
      become: true

    - role: roles/apps/coder
      become: true
      tags: "coder"

    - role: roles/apps/p2p
      bittorrent_downloads_dir: "/external/torrent/downloads"
      become: true
      tags: "p2p"
