---
- hosts: all

  roles:
    - role: roles/system/network
      become: true

    - role: roles/system/ingress
      become: true

    - role: roles/system/containers
      become: true

    - role: roles/apps/adguard
      become: true

    - role: roles/apps/prometheus
      become: true

    - role: prometheus.prometheus.node_exporter
      become: true
      node_exporter_web_listen_address: "172.16.255.254:9100"

    - role: roles/apps/grafana
      become: true
